In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, cdist
import numpy as np
import math
import datetime as dt
from datetime import timedelta
import itertools
from collections import defaultdict
import geopandas as gpd
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "../tests")))

In [2]:
import filters
import daphmeIO as loader
import constants as constants
import stop_detection_modified as SD

## Load data/sample4

```sample4``` has columns representing user ID, longitude, latitude, and datetime.

In [3]:
path = '../data/sample4/'

traj_cols = {'user_id':'user_id',
             'latitude':'dev_lat',
             'longitude':'dev_lon',
             'datetime':'local_datetime'}

sample4 = loader.from_file(path, traj_cols=traj_cols, format='csv')

In [4]:
sample4.head()

             user_id    dev_lat    dev_lon      local_datetime
0    wizardly_joliot  38.321711 -36.667334 2024-01-01 14:29:00
1    wizardly_joliot  38.321676 -36.667365 2024-01-01 14:35:00
2  wonderful_swirles  38.321017 -36.667869 2024-01-01 15:06:00
3   youthful_galileo  38.321625 -36.666612 2024-01-01 08:47:00
4   youthful_galileo  38.321681 -36.666841 2024-01-01 09:59:00

To showcase how the algorithms work in a time efficient manner, we can first filter to one user only.

In [5]:
user_sample4 = sample4[sample4['user_id'] == "angry_spence"]

The data could also come with different formats for spatial and temporal variables:

In [6]:
# Longitude, Latitude, timestamp (unix time)
traj_cols_lon_lat_timestamp = {'user_id':'user_id',
                               'latitude':'dev_lat',
                               'longitude':'dev_lon',
                               'timestamp':'unix_time'}

user_sample4_lon_lat_timestamp = user_sample4.copy()
user_sample4_lon_lat_timestamp['unix_time'] = user_sample4_lon_lat_timestamp['local_datetime'].astype('int64') // 10**9

# x, y, datetime
traj_cols_x_y_datetime = {'user_id':'user_id',
                          'x':'x',
                          'y':'y',
                          'datetime':'local_datetime'}

user_sample4_x_y_datetime = user_sample4.copy()
user_sample4_x_y_datetime = filters.to_projection(user_sample4_x_y_datetime, longitude='dev_lon', latitude='dev_lat')

# x, y, timestamp (unix time)
traj_cols_x_y_timestamp = {'user_id':'user_id',
                          'x':'x',
                          'y':'y',
                          'timestamp':'unix_time'}

user_sample4_x_y_timestamp = user_sample4.copy()
user_sample4_x_y_timestamp = filters.to_projection(user_sample4_x_y_timestamp, longitude='dev_lon', latitude='dev_lat')
user_sample4_x_y_timestamp['unix_time'] = user_sample4_x_y_timestamp['local_datetime'].astype('int64') // 10**9

## Stop Detection Algorithms

### Lachesis

We need to pass some reasonable parameters for:
* ```dur_min```: Minimum duration for a stay in minutes.
* ```dt_max```: Maximum duration permitted between consecutive pings in a stay in minutes (dt_max should be greater than dur_min).
* ```delta_roam```: Maximum roaming distance for a stay in meters.

In [7]:
DUR_MIN = 60
DT_MAX = 120
DELTA_ROAM = 50

Minimum stop table output columns:

In [8]:
SD.lachesis(user_sample4, DUR_MIN, DT_MAX, DELTA_ROAM, traj_cols=traj_cols, complete_output=False)

            start_time        duration          x          y
0  2024-01-01 15:04:00 0 days 01:12:00  -36.66647  38.320064
1  2024-01-01 18:17:00 0 days 02:41:00 -36.667398  38.320415
2  2024-01-01 21:15:00 0 days 03:55:00 -36.667525  38.321253
3  2024-01-02 05:54:00 0 days 02:07:00 -36.667489  38.321273
4  2024-01-02 08:40:00 0 days 03:19:00 -36.667721  38.320554
5  2024-01-03 09:26:00 0 days 01:01:00 -36.667738  38.320675
6  2024-01-03 10:39:00 0 days 01:17:00 -36.667853  38.321051
7  2024-01-03 13:01:00 0 days 04:36:00 -36.667299  38.320045
8  2024-01-03 18:06:00 0 days 07:10:00  -36.66676   38.32098
9  2024-01-04 01:19:00 0 days 01:13:00 -36.667507  38.321394
10 2024-01-04 04:54:00 0 days 03:03:00 -36.667502  38.321389
11 2024-01-04 12:22:00 0 days 01:16:00 -36.666654  38.319718
12 2024-01-04 14:05:00 0 days 01:26:00 -36.667793  38.320045
13 2024-01-04 16:48:00 0 days 01:02:00 -36.667831  38.321119
14 2024-01-04 18:42:00 0 days 06:28:00 -36.666771  38.320966
15 2024-01-05 08:05:00 0 days 02:42:00 -36.667811  38.320681
16 2024-01-05 17:15:00 0 days 01:34:00 -36.667763  38.321814
17 2024-01-05 22:10:00 0 days 01:05:00 -36.667491  38.320426
18 2024-01-06 02:53:00 0 days 05:03:00 -36.667424  38.320448
19 2024-01-06 08:50:00 0 days 01:08:00 -36.667235   38.32013
20 2024-01-06 10:33:00 0 days 01:22:00 -36.667734   38.32073
21 2024-01-06 12:12:00 0 days 01:12:00 -36.667051  38.319685
22 2024-01-06 22:14:00 0 days 04:07:00 -36.666976  38.321385
23 2024-01-07 02:23:00 0 days 04:32:00 -36.666743  38.320984
24 2024-01-07 14:07:00 0 days 03:54:00 -36.667287  38.321782
25 2024-01-08 02:33:00 0 days 05:22:00 -36.667404  38.321417
26 2024-01-08 08:22:00 0 days 01:41:00 -36.667845  38.320605
27 2024-01-08 14:08:00 0 days 03:41:00 -36.667822  38.320691
28 2024-01-08 23:14:00 0 days 08:36:00 -36.667511  38.320957
29 2024-01-09 09:07:00 0 days 02:52:00 -36.667832  38.320679
30 2024-01-09 14:18:00 0 days 03:04:00 -36.667853  38.321107
31 2024-01-10 03:33:00 0 days 02:50:00   -36.6674  38.320404
32 2024-01-10 09:42:00 0 days 01:49:00  -36.66787  38.320669
33 2024-01-10 12:20:00 0 days 01:03:00 -36.666453   38.31968
34 2024-01-10 14:10:00 0 days 03:44:00 -36.667836  38.320587
35 2024-01-10 20:09:00 0 days 01:44:00 -36.666768  38.320981
36 2024-01-11 00:44:00 0 days 07:08:00 -36.666772  38.320959
37 2024-01-11 08:57:00 0 days 03:00:00 -36.667554  38.320036
38 2024-01-11 16:35:00 0 days 01:19:00 -36.666591  38.320192
39 2024-01-11 18:37:00 0 days 03:14:00 -36.667508  38.320972
40 2024-01-12 00:39:00 0 days 03:28:00 -36.667501  38.320973
41 2024-01-12 06:24:00 0 days 01:35:00 -36.667472  38.320984
42 2024-01-12 08:02:00 0 days 02:38:00 -36.666798  38.321656
43 2024-01-12 14:21:00 0 days 03:01:00 -36.667772   38.32062
44 2024-01-12 19:01:00 0 days 10:08:00 -36.666749  38.320986
45 2024-01-13 09:29:00 0 days 02:31:00 -36.667788  38.320604
46 2024-01-13 15:06:00 0 days 01:39:00 -36.666563  38.320812
47 2024-01-14 01:45:00 0 days 06:07:00 -36.666764  38.320952
48 2024-01-14 14:10:00 0 days 03:51:00 -36.667191  38.319982
49 2024-01-14 19:45:00 0 days 12:05:00 -36.667436  38.320446

All stop table output columns:

In [9]:
SD.lachesis(user_sample4, DUR_MIN, DT_MAX, DELTA_ROAM, traj_cols=traj_cols, complete_output=True)

,start_time,end_time,x,y,diameter,n_pings,duration
0,2024-01-01 15:04:00,2024-01-01 16:16:00,-36.66647,38.320064,14.691535,14,0 days 01:12:00
1,2024-01-01 18:17:00,2024-01-01 20:58:00,-36.667398,38.320415,12.974932,19,0 days 02:41:00
2,2024-01-01 21:15:00,2024-01-02 01:10:00,-36.667525,38.321253,13.946715,32,0 days 03:55:00
3,2024-01-02 05:54:00,2024-01-02 08:01:00,-36.667489,38.321273,31.46013,17,0 days 02:07:00
4,2024-01-02 08:40:00,2024-01-02 11:59:00,-36.667721,38.320554,20.736412,39,0 days 03:19:00
5,2024-01-03 09:26:00,2024-01-03 10:27:00,-36.667738,38.320675,49.433588,12,0 days 01:01:00
6,2024-01-03 10:39:00,2024-01-03 11:56:00,-36.667853,38.321051,24.082471,8,0 days 01:17:00
7,2024-01-03 13:01:00,2024-01-03 17:37:00,-36.667299,38.320045,47.749101,44,0 days 04:36:00
8,2024-01-03 18:06:00,2024-01-04 01:16:00,-36.66676,38.32098,33.545006,48,0 days 07:10:00
9,2024-01-04 01:19:00,2024-01-04 02:32:00,-36.667507,38.321394,16.765689,15,0 days 01:13:00
10,2024-01-04 04:54:00,2024-01-04 07:57:00,-36.667502,38.321389,16.362749,31,0 days 03:03:00
11,2024-01-04 12:22:00,2024-01-04 13:38:00,-36.666654,38.319718,33.397567,10,0 days 01:16:00
12,2024-01-04 14:05:00,2024-01-04 15:31:00,-36.667793,38.320045,26.048912,21,0 days 01:26:00
13,2024-01-04 16:48:00,2024-01-04 17:50:00,-36.667831,38.321119,9.941362,15,0 days 01:02:00
14,2024-01-04 18:42:00,2024-01-05 01:10:00,-36.666771,38.320966,17.173805,46,0 days 06:28:00
15,2024-01-05 08:05:00,2024-01-05 10:47:00,-36.667811,38.320681,32.54632,17,0 days 02:42:00
16,2024-01-05 17:15:00,2024-01-05 18:49:00,-36.667763,38.321814,46.139155,20,0 days 01:34:00
17,2024-01-05 22:10:00,2024-01-05 23:15:00,-36.667491,38.320426,13.51992,11,0 days 01:05:00
18,2024-01-06 02:53:00,2024-01-06 07:56:00,-36.667424,38.320448,23.781001,49,0 days 05:03:00
19,2024-01-06 08:50:00,2024-01-06 09:58:00,-36.667235,38.32013,48.187099,9,0 days 01:08:00
20,2024-01-06 10:33:00,2024-01-06 11:55:00,-36.667734,38.32073,18.848479,11,0 days 01:22:00
21,2024-01-06 12:12:00,2024-01-06 13:24:00,-36.667051,38.319685,31.644363,12,0 days 01:12:00
22,2024-01-06 22:14:00,2024-01-07 02:21:00,-36.666976,38.321385,46.410857,33,0 days 04:07:00
23,2024-01-07 02:23:00,2024-01-07 06:55:00,-36.666743,38.320984,15.327889,43,0 days 04:32:00
24,2024-01-07 14:07:00,2024-01-07 18:01:00,-36.667287,38.321782,24.090289,42,0 days 03:54:00
25,2024-01-08 02:33:00,2024-01-08 07:55:00,-36.667404,38.321417,15.187481,41,0 days 05:22:00
26,2024-01-08 08:22:00,2024-01-08 10:03:00,-36.667845,38.320605,41.718132,16,0 days 01:41:00
27,2024-01-08 14:08:00,2024-01-08 17:49:00,-36.667822,38.320691,27.395906,35,0 days 03:41:00
28,2024-01-08 23:14:00,2024-01-09 07:50:00,-36.667511,38.320957,23.768352,62,0 days 08:36:00
29,2024-01-09 09:07:00,2024-01-09 11:59:00,-36.667832,38.320679,15.375278,19,0 days 02:52:00
30,2024-01-09 14:18:00,2024-01-09 17:22:00,-36.667853,38.321107,19.5768,27,0 days 03:04:00
31,2024-01-10 03:33:00,2024-01-10 06:23:00,-36.6674,38.320404,15.939312,27,0 days 02:50:00
32,2024-01-10 09:42:00,2024-01-10 11:31:00,-36.66787,38.320669,18.235561,13,0 days 01:49:00
33,2024-01-10 12:20:00,2024-01-10 13:23:00,-36.666453,38.31968,45.984901,7,0 days 01:03:00
34,2024-01-10 14:10:00,2024-01-10 17:54:00,-36.667836,38.320587,29.498767,40,0 days 03:44:00
35,2024-01-10 20:09:00,2024-01-10 21:53:00,-36.666768,38.320981,15.781151,24,0 days 01:44:00
36,2024-01-11 00:44:00,2024-01-11 07:52:00,-36.666772,38.320959,15.238643,53,0 days 07:08:00
37,2024-01-11 08:57:00,2024-01-11 11:57:00,-36.667554,38.320036,21.862976,25,0 days 03:00:00
38,2024-01-11 16:35:00,2024-01-11 17:54:00,-36.666591,38.320192,12.920852,16,0 days 01:19:00
39,2024-01-11 18:37:00,2024-01-11 21:51:00,-36.667508,38.320972,8.199704,16,0 days 03:14:00
40,2024-01-12 00:39:00,2024-01-12 04:07:00,-36.667501,38.320973,13.142851,19,0 days 03:28:00
41,2024-01-12 06:24:00,2024-01-12 07:59:00,-36.667472,38.320984,10.926358,15,0 days 01:35:00
42,2024-01-12 08:02:00,2024-01-12 10:40:00,-36.666798,38.321656,42.543583,22,0 days 02:38:00
43,2024-01-12 14:21:00,2024-01-12 17:22:00,-36.667772,38.32062,23.163889,17,0 days 03:01:00
44,2024-01-12 19:01:00,2024-01-13 05:09:00,-36.666749,38.320986,16.033713,84,0 days 10:08:00
45,2024-01-13 09:29:00,2024-01-13 12:00:00,-36.667788,38.320604,28.621842,22,0 days 02:31:00
46,2024-01-13 15:06:00,2024-01-13 16:45:00,-36.666563,38.320812,17.186422,17,0 days 01:39:00
47,2024-01-14 01:45:00,2024-01-14 07:52:00,-36.666764,38.320952,13.814779,57,0 days 06:07:00
48,2024-01-14 14:10:00,2024-01-14 18:01:00,-36.667191,38.319982,34.917063,17,0 days 03:51:00
49,2024-01-14 19:45:00,2024-01-15 07:50:00,-36.667436,38.320446,22.775558,88,0 days 12:05:00

Lachesis with longitude, latitude, and timestamp (unix time):

In [10]:
SD.lachesis(user_sample4_lon_lat_timestamp, DUR_MIN, DT_MAX, DELTA_ROAM, traj_cols=traj_cols_lon_lat_timestamp, complete_output=False)

      start_time  duration          x          y
0   1.704121e+09    4320.0 -36.666470  38.320064
1   1.704133e+09    9660.0 -36.667398  38.320415
2   1.704144e+09   14100.0 -36.667525  38.321253
3   1.704175e+09    7620.0 -36.667489  38.321273
4   1.704185e+09   11940.0 -36.667721  38.320554
5   1.704274e+09    3660.0 -36.667738  38.320675
6   1.704278e+09    4620.0 -36.667853  38.321051
7   1.704287e+09   16560.0 -36.667299  38.320045
8   1.704305e+09   25800.0 -36.666760  38.320980
9   1.704331e+09    4380.0 -36.667507  38.321394
10  1.704344e+09   10980.0 -36.667502  38.321389
11  1.704371e+09    4560.0 -36.666654  38.319718
12  1.704377e+09    5160.0 -36.667793  38.320045
13  1.704387e+09    3720.0 -36.667831  38.321119
14  1.704394e+09   23280.0 -36.666771  38.320966
15  1.704442e+09    9720.0 -36.667811  38.320681
16  1.704475e+09    5640.0 -36.667763  38.321814
17  1.704493e+09    3900.0 -36.667491  38.320426
18  1.704510e+09   18180.0 -36.667424  38.320448
19  1.704531e+09    4080.0 -36.667235  38.320130
20  1.704537e+09    4920.0 -36.667734  38.320730
21  1.704543e+09    4320.0 -36.667051  38.319685
22  1.704579e+09   14820.0 -36.666976  38.321385
23  1.704594e+09   16320.0 -36.666743  38.320984
24  1.704636e+09   14040.0 -36.667287  38.321782
25  1.704681e+09   19320.0 -36.667404  38.321417
26  1.704702e+09    6060.0 -36.667845  38.320605
27  1.704723e+09   13260.0 -36.667822  38.320691
28  1.704756e+09   30960.0 -36.667511  38.320957
29  1.704791e+09   10320.0 -36.667832  38.320679
30  1.704810e+09   11040.0 -36.667853  38.321107
31  1.704858e+09   10200.0 -36.667400  38.320404
32  1.704880e+09    6540.0 -36.667870  38.320669
33  1.704889e+09    3780.0 -36.666453  38.319680
34  1.704896e+09   13440.0 -36.667836  38.320587
35  1.704917e+09    6240.0 -36.666768  38.320981
36  1.704934e+09   25680.0 -36.666772  38.320959
37  1.704963e+09   10800.0 -36.667554  38.320036
38  1.704991e+09    4740.0 -36.666591  38.320192
39  1.704998e+09   11640.0 -36.667508  38.320972
40  1.705020e+09   12480.0 -36.667501  38.320973
41  1.705041e+09    5700.0 -36.667472  38.320984
42  1.705047e+09    9480.0 -36.666798  38.321656
43  1.705069e+09   10860.0 -36.667772  38.320620
44  1.705086e+09   36480.0 -36.666749  38.320986
45  1.705138e+09    9060.0 -36.667788  38.320604
46  1.705158e+09    5940.0 -36.666563  38.320812
47  1.705197e+09   22020.0 -36.666764  38.320952
48  1.705241e+09   13860.0 -36.667191  38.319982
49  1.705262e+09   43500.0 -36.667436  38.320446

Lachesis with x, y, and timestamp (unix time):

In [11]:
SD.lachesis(user_sample4_x_y_timestamp, DUR_MIN, DT_MAX, DELTA_ROAM, traj_cols=traj_cols_x_y_timestamp, complete_output=False)

      start_time  duration             x             y
0   1.704121e+09    4320.0 -4.081693e+06  4.624739e+06
1   1.704133e+09    9660.0 -4.081796e+06  4.624789e+06
2   1.704144e+09   14100.0 -4.081810e+06  4.624908e+06
3   1.704175e+09    7620.0 -4.081806e+06  4.624911e+06
4   1.704185e+09   11940.0 -4.081832e+06  4.624809e+06
5   1.704276e+09    6660.0 -4.081845e+06  4.624889e+06
6   1.704291e+09   12960.0 -4.081785e+06  4.624737e+06
7   1.704305e+09   25800.0 -4.081725e+06  4.624869e+06
8   1.704331e+09    4380.0 -4.081808e+06  4.624928e+06
9   1.704344e+09   10980.0 -4.081808e+06  4.624927e+06
10  1.704372e+09    3960.0 -4.081713e+06  4.624690e+06
11  1.704377e+09    5160.0 -4.081840e+06  4.624737e+06
12  1.704387e+09    3720.0 -4.081844e+06  4.624889e+06
13  1.704394e+09   23280.0 -4.081726e+06  4.624867e+06
14  1.704442e+09    9720.0 -4.081842e+06  4.624827e+06
15  1.704479e+09    4020.0 -4.081871e+06  4.624974e+06
16  1.704493e+09    3900.0 -4.081806e+06  4.624791e+06
17  1.704510e+09   18180.0 -4.081799e+06  4.624794e+06
18  1.704532e+09    5100.0 -4.081793e+06  4.624755e+06
19  1.704537e+09    4920.0 -4.081834e+06  4.624834e+06
20  1.704543e+09    4320.0 -4.081757e+06  4.624685e+06
21  1.704579e+09   12480.0 -4.081749e+06  4.624927e+06
22  1.704594e+09   16740.0 -4.081723e+06  4.624870e+06
23  1.704636e+09   14040.0 -4.081785e+06  4.624983e+06
24  1.704681e+09   19320.0 -4.081797e+06  4.624931e+06
25  1.704703e+09    5580.0 -4.081844e+06  4.624816e+06
26  1.704723e+09   13260.0 -4.081843e+06  4.624828e+06
27  1.704756e+09   30960.0 -4.081809e+06  4.624866e+06
28  1.704791e+09   10320.0 -4.081844e+06  4.624827e+06
29  1.704810e+09   11040.0 -4.081847e+06  4.624887e+06
30  1.704858e+09   10200.0 -4.081796e+06  4.624788e+06
31  1.704880e+09    6540.0 -4.081849e+06  4.624825e+06
32  1.704896e+09   13440.0 -4.081845e+06  4.624814e+06
33  1.704917e+09    6240.0 -4.081726e+06  4.624869e+06
34  1.704934e+09   25680.0 -4.081726e+06  4.624866e+06
35  1.704963e+09   10800.0 -4.081813e+06  4.624735e+06
36  1.704991e+09    4740.0 -4.081706e+06  4.624757e+06
37  1.704998e+09   11640.0 -4.081808e+06  4.624868e+06
38  1.705020e+09   12480.0 -4.081808e+06  4.624868e+06
39  1.705041e+09    5700.0 -4.081804e+06  4.624870e+06
40  1.705047e+09    9480.0 -4.081729e+06  4.624965e+06
41  1.705069e+09   10860.0 -4.081838e+06  4.624818e+06
42  1.705086e+09   36480.0 -4.081724e+06  4.624870e+06
43  1.705138e+09    9060.0 -4.081840e+06  4.624816e+06
44  1.705158e+09    5940.0 -4.081703e+06  4.624845e+06
45  1.705197e+09   22020.0 -4.081725e+06  4.624865e+06
46  1.705241e+09   13860.0 -4.081773e+06  4.624728e+06
47  1.705262e+09   43500.0 -4.081802e+06  4.624791e+06

Lachesis with x, y, and datetime:

In [12]:
SD.lachesis(user_sample4_x_y_datetime, DUR_MIN, DT_MAX, DELTA_ROAM, traj_cols=traj_cols_x_y_datetime, complete_output=False)

            start_time        duration               x               y
0  2024-01-01 15:04:00 0 days 01:12:00 -4081692.766601  4624739.339131
1  2024-01-01 18:17:00 0 days 02:41:00 -4081796.107506  4624789.158858
2  2024-01-01 21:15:00 0 days 03:55:00 -4081810.192229  4624907.987139
3  2024-01-02 05:54:00 0 days 02:07:00 -4081806.158897  4624910.902451
4  2024-01-02 08:40:00 0 days 03:19:00 -4081832.070485  4624808.802068
5  2024-01-03 10:05:00 0 days 01:51:00 -4081844.834337  4624889.002115
6  2024-01-03 14:03:00 0 days 03:36:00 -4081785.058141  4624736.681099
7  2024-01-03 18:06:00 0 days 07:10:00 -4081725.097327  4624869.336981
8  2024-01-04 01:19:00 0 days 01:13:00 -4081808.204314   4624927.97637
9  2024-01-04 04:54:00 0 days 03:03:00 -4081807.596107  4624927.360419
10 2024-01-04 12:32:00 0 days 01:06:00 -4081713.259183  4624690.178763
11 2024-01-04 14:05:00 0 days 01:26:00 -4081840.067392  4624736.661607
12 2024-01-04 16:48:00 0 days 01:02:00 -4081844.241437  4624888.954845
13 2024-01-04 18:42:00 0 days 06:28:00 -4081726.241635  4624867.312201
14 2024-01-05 08:05:00 0 days 02:42:00 -4081842.055588  4624826.841674
15 2024-01-05 18:16:00 0 days 01:07:00 -4081871.051488   4624973.96579
16 2024-01-05 22:10:00 0 days 01:05:00    -4081806.478  4624790.663652
17 2024-01-06 02:53:00 0 days 05:03:00 -4081798.928129  4624793.807209
18 2024-01-06 09:01:00 0 days 01:25:00 -4081793.375782  4624754.717193
19 2024-01-06 10:33:00 0 days 01:22:00 -4081833.531214  4624833.768369
20 2024-01-06 12:12:00 0 days 01:12:00 -4081757.483998  4624685.497163
21 2024-01-06 22:14:00 0 days 03:28:00 -4081749.110941  4624926.692816
22 2024-01-07 02:16:00 0 days 04:39:00 -4081723.160234  4624869.809522
23 2024-01-07 14:07:00 0 days 03:54:00 -4081784.995611   4624982.73781
24 2024-01-08 02:33:00 0 days 05:22:00 -4081796.690519  4624931.299499
25 2024-01-08 08:30:00 0 days 01:33:00 -4081843.698498   4624816.18885
26 2024-01-08 14:08:00 0 days 03:41:00  -4081843.32912  4624828.327139
27 2024-01-08 23:14:00 0 days 08:36:00 -4081808.599645  4624866.045867
28 2024-01-09 09:07:00 0 days 02:52:00 -4081844.388321  4624826.590154
29 2024-01-09 14:18:00 0 days 03:04:00 -4081846.769604  4624887.257613
30 2024-01-10 03:33:00 0 days 02:50:00 -4081796.295641  4624787.580564
31 2024-01-10 09:42:00 0 days 01:49:00 -4081848.606295  4624825.087638
32 2024-01-10 14:10:00 0 days 03:44:00 -4081844.827443  4624813.510022
33 2024-01-10 20:09:00 0 days 01:44:00 -4081725.969668  4624869.383336
34 2024-01-11 00:44:00 0 days 07:08:00  -4081726.38541  4624866.329794
35 2024-01-11 08:57:00 0 days 03:00:00 -4081813.466188  4624735.329076
36 2024-01-11 16:35:00 0 days 01:19:00 -4081706.258198  4624757.427176
37 2024-01-11 18:37:00 0 days 03:14:00 -4081808.326895  4624868.198321
38 2024-01-12 00:39:00 0 days 03:28:00 -4081807.547209  4624868.309283
39 2024-01-12 06:24:00 0 days 01:35:00 -4081804.300731  4624869.869128
40 2024-01-12 08:02:00 0 days 02:38:00 -4081729.314406  4624965.199198
41 2024-01-12 14:21:00 0 days 03:01:00 -4081837.690717  4624818.192041
42 2024-01-12 19:01:00 0 days 10:08:00 -4081723.813889  4624870.186272
43 2024-01-13 09:29:00 0 days 02:31:00 -4081839.514392  4624815.964452
44 2024-01-13 15:06:00 0 days 01:39:00 -4081703.080909  4624845.435014
45 2024-01-14 01:45:00 0 days 06:07:00 -4081725.485597  4624865.372977
46 2024-01-14 14:10:00 0 days 03:51:00 -4081773.083786  4624727.608046
47 2024-01-14 19:45:00 0 days 12:05:00 -4081801.955845  4624790.715472

### Temporal DBSCAN

We need to pass some reasonable parameters for:
* ```time_thresh```: Time threshold in minutes for identifying neighbors.
* ```dist_thresh```: Distance threshold in meters for identifying neighbors.
* ```min_pts```: Minimum number of points required to form a dense region (core point).

In [13]:
TIME_THRESH = 100
DIST_THRESH = 40
MIN_PTS = 10

We can get the final cluster and core labels for each of the data points:

In [14]:
SD._temporal_dbscan_labels(user_sample4, TIME_THRESH, DIST_THRESH, MIN_PTS, complete_output=False, traj_cols=traj_cols)

                     cluster  core
2024-01-01 10:21:00       -1    -1
2024-01-01 10:27:00       -1    -1
2024-01-01 10:29:00       -1    -1
2024-01-01 10:39:00       -1    -1
2024-01-01 10:42:00       -1    -1
...                      ...   ...
2024-01-15 07:23:00        1     1
2024-01-15 07:29:00        1     1
2024-01-15 07:33:00        1     1
2024-01-15 07:39:00        1     1
2024-01-15 07:50:00       -1    -1

[1696 rows x 2 columns]

Or we can also get a stop table:

In [15]:
SD.temporal_dbscan(user_sample4, TIME_THRESH, DIST_THRESH, MIN_PTS, complete_output=False, traj_cols=traj_cols)

                 start_time        duration         x         y
cluster
0       2024-01-04 16:02:00 0 days 00:43:00 -0.639973  0.668841
1       2024-01-14 19:45:00 0 days 11:54:00 -0.639968  0.668818
2       2024-01-14 14:10:00 0 days 01:29:00 -0.639963  0.668810
3       2024-01-14 01:45:00 0 days 06:07:00 -0.639956  0.668827
4       2024-01-13 13:53:00 0 days 02:52:00 -0.639952  0.668824
5       2024-01-13 09:29:00 0 days 02:31:00 -0.639974  0.668821
6       2024-01-12 19:01:00 0 days 10:08:00 -0.639956  0.668827
7       2024-01-12 14:49:00 0 days 02:33:00 -0.639974  0.668820
8       2024-01-12 08:02:00 0 days 02:38:00 -0.639956  0.668839
9       2024-01-12 06:24:00 0 days 01:35:00 -0.639968  0.668827
10      2024-01-12 00:39:00 0 days 03:28:00 -0.639968  0.668827
11      2024-01-11 16:35:00 0 days 01:43:00 -0.639953  0.668813
12      2024-01-11 08:57:00 0 days 03:00:00 -0.639970  0.668811
13      2024-01-11 00:44:00 0 days 07:08:00 -0.639956  0.668827
14      2024-01-10 20:09:00 0 days 01:44:00 -0.639956  0.668827
15      2024-01-10 14:10:00 0 days 04:12:00 -0.639974  0.668820
16      2024-01-10 09:42:00 0 days 01:49:00 -0.639975  0.668822
17      2024-01-10 03:33:00 0 days 02:50:00 -0.639967  0.668817
18      2024-01-09 14:18:00 0 days 03:04:00 -0.639975  0.668829
19      2024-01-09 06:51:00 0 days 05:42:00 -0.639974  0.668823
20      2024-01-08 23:14:00 0 days 05:54:00 -0.639969  0.668827
21      2024-01-08 14:08:00 0 days 04:10:00 -0.639974  0.668822
22      2024-01-08 08:22:00 0 days 01:41:00 -0.639975  0.668821
23      2024-01-08 07:11:00 0 days 00:44:00 -0.639967  0.668835
24      2024-01-08 02:33:00 0 days 02:39:00 -0.639967  0.668834
25      2024-01-07 14:07:00 0 days 03:54:00 -0.639965  0.668841
26      2024-01-07 11:12:00 0 days 02:17:00 -0.639975  0.668820
27      2024-01-06 22:14:00 0 days 08:41:00 -0.639956  0.668828
28      2024-01-06 12:12:00 0 days 01:12:00 -0.639961  0.668804
29      2024-01-06 10:33:00 0 days 01:22:00 -0.639973  0.668823
30      2024-01-06 02:53:00 0 days 07:33:00 -0.639967  0.668818
31      2024-01-05 22:10:00 0 days 01:05:00 -0.639968  0.668818
32      2024-01-05 17:15:00 0 days 02:08:00 -0.639973  0.668842
33      2024-01-05 08:05:00 0 days 03:37:00 -0.639974  0.668823
34      2024-01-04 23:39:00 0 days 01:31:00 -0.639956  0.668827
35      2024-01-04 18:42:00 0 days 03:01:00 -0.639956  0.668827
36      2024-01-04 16:48:00 0 days 01:02:00 -0.639975  0.668830
37      2024-01-04 14:05:00 0 days 01:26:00 -0.639974  0.668811
38      2024-01-04 04:54:00 0 days 03:03:00 -0.639969  0.668834
39      2024-01-04 01:19:00 0 days 01:13:00 -0.639969  0.668834
40      2024-01-03 20:05:00 0 days 05:11:00 -0.639956  0.668827
41      2024-01-03 13:01:00 0 days 04:38:00 -0.639965  0.668811
42      2024-01-03 10:05:00 0 days 02:12:00 -0.639975  0.668830
43      2024-01-03 09:04:00 0 days 00:37:00 -0.639973  0.668821
44      2024-01-03 08:04:00 0 days 00:54:00 -0.639969  0.668804
45      2024-01-02 08:40:00 0 days 03:19:00 -0.639972  0.668820
46      2024-01-02 05:54:00 0 days 02:07:00 -0.639969  0.668833
47      2024-01-01 21:15:00 0 days 03:55:00 -0.639969  0.668832
48      2024-01-01 18:17:00 0 days 02:41:00 -0.639967  0.668817
49      2024-01-01 15:04:00 0 days 01:12:00 -0.639951  0.668811

Temporal DBSCAN with longitude, latitude, and timestamp (unix time):

In [16]:
SD.temporal_dbscan(user_sample4_lon_lat_timestamp, TIME_THRESH, DIST_THRESH, MIN_PTS, complete_output=False, traj_cols=traj_cols_lon_lat_timestamp)

           start_time  duration         x         y
cluster
0        1.704384e+09    2580.0 -0.639973  0.668841
1        1.705262e+09   42840.0 -0.639968  0.668818
2        1.705241e+09    5340.0 -0.639963  0.668810
3        1.705197e+09   22020.0 -0.639956  0.668827
4        1.705154e+09   10320.0 -0.639952  0.668824
5        1.705138e+09    9060.0 -0.639974  0.668821
6        1.705086e+09   36480.0 -0.639956  0.668827
7        1.705071e+09    9180.0 -0.639974  0.668820
8        1.705047e+09    9480.0 -0.639956  0.668839
9        1.705041e+09    5700.0 -0.639968  0.668827
10       1.705020e+09   12480.0 -0.639968  0.668827
11       1.704991e+09    6180.0 -0.639953  0.668813
12       1.704963e+09   10800.0 -0.639970  0.668811
13       1.704934e+09   25680.0 -0.639956  0.668827
14       1.704917e+09    6240.0 -0.639956  0.668827
15       1.704896e+09   15120.0 -0.639974  0.668820
16       1.704880e+09    6540.0 -0.639975  0.668822
17       1.704858e+09   10200.0 -0.639967  0.668817
18       1.704810e+09   11040.0 -0.639975  0.668829
19       1.704783e+09   20520.0 -0.639974  0.668823
20       1.704756e+09   21240.0 -0.639969  0.668827
21       1.704723e+09   15000.0 -0.639974  0.668822
22       1.704702e+09    6060.0 -0.639975  0.668821
23       1.704698e+09    2640.0 -0.639967  0.668835
24       1.704681e+09    9540.0 -0.639967  0.668834
25       1.704636e+09   14040.0 -0.639965  0.668841
26       1.704626e+09    8220.0 -0.639975  0.668820
27       1.704579e+09   31260.0 -0.639956  0.668828
28       1.704543e+09    4320.0 -0.639961  0.668804
29       1.704537e+09    4920.0 -0.639973  0.668823
30       1.704510e+09   27180.0 -0.639967  0.668818
31       1.704493e+09    3900.0 -0.639968  0.668818
32       1.704475e+09    7680.0 -0.639973  0.668842
33       1.704442e+09   13020.0 -0.639974  0.668823
34       1.704412e+09    5460.0 -0.639956  0.668827
35       1.704394e+09   10860.0 -0.639956  0.668827
36       1.704387e+09    3720.0 -0.639975  0.668830
37       1.704377e+09    5160.0 -0.639974  0.668811
38       1.704344e+09   10980.0 -0.639969  0.668834
39       1.704331e+09    4380.0 -0.639969  0.668834
40       1.704312e+09   18660.0 -0.639956  0.668827
41       1.704287e+09   16680.0 -0.639965  0.668811
42       1.704276e+09    7920.0 -0.639975  0.668830
43       1.704273e+09    2220.0 -0.639973  0.668821
44       1.704269e+09    3240.0 -0.639969  0.668804
45       1.704185e+09   11940.0 -0.639972  0.668820
46       1.704175e+09    7620.0 -0.639969  0.668833
47       1.704144e+09   14100.0 -0.639969  0.668832
48       1.704133e+09    9660.0 -0.639967  0.668817
49       1.704121e+09    4320.0 -0.639951  0.668811

Temporal DBSCAN with x, y, and timestamp (unix time):

In [17]:
SD.temporal_dbscan(user_sample4_x_y_timestamp, TIME_THRESH, DIST_THRESH, MIN_PTS, complete_output=False, traj_cols=traj_cols_x_y_timestamp)

           start_time  duration             x             y
cluster
0        1.704384e+09    2580.0 -4.081836e+06  4.624984e+06
1        1.705262e+09   42840.0 -4.081802e+06  4.624791e+06
2        1.705241e+09    5340.0 -4.081771e+06  4.624728e+06
3        1.705197e+09   22020.0 -4.081725e+06  4.624865e+06
4        1.705158e+09    5940.0 -4.081703e+06  4.624845e+06
5        1.705138e+09    9060.0 -4.081840e+06  4.624816e+06
6        1.705086e+09   36480.0 -4.081724e+06  4.624870e+06
7        1.705071e+09    9180.0 -4.081839e+06  4.624814e+06
8        1.705047e+09    9480.0 -4.081729e+06  4.624965e+06
9        1.705041e+09    5700.0 -4.081804e+06  4.624870e+06
10       1.705020e+09   12480.0 -4.081808e+06  4.624868e+06
11       1.704991e+09    6180.0 -4.081706e+06  4.624757e+06
12       1.704963e+09   10800.0 -4.081813e+06  4.624735e+06
13       1.704934e+09   25680.0 -4.081726e+06  4.624866e+06
14       1.704917e+09    6240.0 -4.081726e+06  4.624869e+06
15       1.704896e+09   15120.0 -4.081845e+06  4.624814e+06
16       1.704880e+09    6540.0 -4.081849e+06  4.624825e+06
17       1.704858e+09   10200.0 -4.081796e+06  4.624788e+06
18       1.704810e+09   11040.0 -4.081847e+06  4.624887e+06
19       1.704783e+09   20520.0 -4.081838e+06  4.624835e+06
20       1.704756e+09   21240.0 -4.081808e+06  4.624870e+06
21       1.704723e+09   15000.0 -4.081843e+06  4.624828e+06
22       1.704702e+09    6060.0 -4.081846e+06  4.624816e+06
23       1.704698e+09    2640.0 -4.081796e+06  4.624934e+06
24       1.704681e+09    9540.0 -4.081796e+06  4.624928e+06
25       1.704636e+09   14040.0 -4.081785e+06  4.624983e+06
26       1.704626e+09    5700.0 -4.081846e+06  4.624813e+06
27       1.704594e+09   16740.0 -4.081723e+06  4.624870e+06
28       1.704579e+09   12480.0 -4.081749e+06  4.624927e+06
29       1.704543e+09    4320.0 -4.081757e+06  4.624685e+06
30       1.704537e+09    4920.0 -4.081834e+06  4.624834e+06
31       1.704532e+09    5100.0 -4.081793e+06  4.624755e+06
32       1.704529e+09    2820.0 -4.081765e+06  4.624681e+06
33       1.704510e+09   18180.0 -4.081799e+06  4.624794e+06
34       1.704493e+09    3900.0 -4.081806e+06  4.624791e+06
35       1.704475e+09    7680.0 -4.081837e+06  4.624988e+06
36       1.704442e+09   13020.0 -4.081842e+06  4.624834e+06
37       1.704412e+09    5460.0 -4.081728e+06  4.624868e+06
38       1.704394e+09   10860.0 -4.081729e+06  4.624866e+06
39       1.704387e+09    3720.0 -4.081844e+06  4.624889e+06
40       1.704377e+09    5160.0 -4.081840e+06  4.624737e+06
41       1.704344e+09   10980.0 -4.081808e+06  4.624927e+06
42       1.704331e+09    4380.0 -4.081808e+06  4.624928e+06
43       1.704312e+09   18660.0 -4.081726e+06  4.624871e+06
44       1.704291e+09   12960.0 -4.081785e+06  4.624737e+06
45       1.704276e+09    7920.0 -4.081846e+06  4.624892e+06
46       1.704273e+09    1920.0 -4.081835e+06  4.624822e+06
47       1.704269e+09    3120.0 -4.081811e+06  4.624681e+06
48       1.704185e+09   11940.0 -4.081832e+06  4.624809e+06
49       1.704175e+09    7620.0 -4.081806e+06  4.624911e+06
50       1.704144e+09   14100.0 -4.081810e+06  4.624908e+06
51       1.704133e+09    9660.0 -4.081796e+06  4.624789e+06
52       1.704121e+09    4320.0 -4.081693e+06  4.624739e+06

Temporal DBSCAN with x, y, and datetime:

In [18]:
SD.temporal_dbscan(user_sample4_x_y_datetime, TIME_THRESH, DIST_THRESH, MIN_PTS, complete_output=False, traj_cols=traj_cols_x_y_datetime)

                 start_time        duration             x             y
cluster
0       2024-01-04 16:02:00 0 days 00:43:00 -4.081836e+06  4.624984e+06
1       2024-01-14 19:45:00 0 days 11:54:00 -4.081802e+06  4.624791e+06
2       2024-01-14 14:10:00 0 days 01:29:00 -4.081771e+06  4.624728e+06
3       2024-01-14 01:45:00 0 days 06:07:00 -4.081725e+06  4.624865e+06
4       2024-01-13 15:06:00 0 days 01:39:00 -4.081703e+06  4.624845e+06
5       2024-01-13 09:29:00 0 days 02:31:00 -4.081840e+06  4.624816e+06
6       2024-01-12 19:01:00 0 days 10:08:00 -4.081724e+06  4.624870e+06
7       2024-01-12 14:49:00 0 days 02:33:00 -4.081839e+06  4.624814e+06
8       2024-01-12 08:02:00 0 days 02:38:00 -4.081729e+06  4.624965e+06
9       2024-01-12 06:24:00 0 days 01:35:00 -4.081804e+06  4.624870e+06
10      2024-01-12 00:39:00 0 days 03:28:00 -4.081808e+06  4.624868e+06
11      2024-01-11 16:35:00 0 days 01:43:00 -4.081706e+06  4.624757e+06
12      2024-01-11 08:57:00 0 days 03:00:00 -4.081813e+06  4.624735e+06
13      2024-01-11 00:44:00 0 days 07:08:00 -4.081726e+06  4.624866e+06
14      2024-01-10 20:09:00 0 days 01:44:00 -4.081726e+06  4.624869e+06
15      2024-01-10 14:10:00 0 days 04:12:00 -4.081845e+06  4.624814e+06
16      2024-01-10 09:42:00 0 days 01:49:00 -4.081849e+06  4.624825e+06
17      2024-01-10 03:33:00 0 days 02:50:00 -4.081796e+06  4.624788e+06
18      2024-01-09 14:18:00 0 days 03:04:00 -4.081847e+06  4.624887e+06
19      2024-01-09 06:51:00 0 days 05:42:00 -4.081838e+06  4.624835e+06
20      2024-01-08 23:14:00 0 days 05:54:00 -4.081808e+06  4.624870e+06
21      2024-01-08 14:08:00 0 days 04:10:00 -4.081843e+06  4.624828e+06
22      2024-01-08 08:22:00 0 days 01:41:00 -4.081846e+06  4.624816e+06
23      2024-01-08 07:11:00 0 days 00:44:00 -4.081796e+06  4.624934e+06
24      2024-01-08 02:33:00 0 days 02:39:00 -4.081796e+06  4.624928e+06
25      2024-01-07 14:07:00 0 days 03:54:00 -4.081785e+06  4.624983e+06
26      2024-01-07 11:12:00 0 days 01:35:00 -4.081846e+06  4.624813e+06
27      2024-01-07 02:16:00 0 days 04:39:00 -4.081723e+06  4.624870e+06
28      2024-01-06 22:14:00 0 days 03:28:00 -4.081749e+06  4.624927e+06
29      2024-01-06 12:12:00 0 days 01:12:00 -4.081757e+06  4.624685e+06
30      2024-01-06 10:33:00 0 days 01:22:00 -4.081834e+06  4.624834e+06
31      2024-01-06 09:01:00 0 days 01:25:00 -4.081793e+06  4.624755e+06
32      2024-01-06 08:13:00 0 days 00:47:00 -4.081765e+06  4.624681e+06
33      2024-01-06 02:53:00 0 days 05:03:00 -4.081799e+06  4.624794e+06
34      2024-01-05 22:10:00 0 days 01:05:00 -4.081806e+06  4.624791e+06
35      2024-01-05 17:15:00 0 days 02:08:00 -4.081837e+06  4.624988e+06
36      2024-01-05 08:05:00 0 days 03:37:00 -4.081842e+06  4.624834e+06
37      2024-01-04 23:39:00 0 days 01:31:00 -4.081728e+06  4.624868e+06
38      2024-01-04 18:42:00 0 days 03:01:00 -4.081729e+06  4.624866e+06
39      2024-01-04 16:48:00 0 days 01:02:00 -4.081844e+06  4.624889e+06
40      2024-01-04 14:05:00 0 days 01:26:00 -4.081840e+06  4.624737e+06
41      2024-01-04 04:54:00 0 days 03:03:00 -4.081808e+06  4.624927e+06
42      2024-01-04 01:19:00 0 days 01:13:00 -4.081808e+06  4.624928e+06
43      2024-01-03 20:05:00 0 days 05:11:00 -4.081726e+06  4.624871e+06
44      2024-01-03 14:03:00 0 days 03:36:00 -4.081785e+06  4.624737e+06
45      2024-01-03 10:05:00 0 days 02:12:00 -4.081846e+06  4.624892e+06
46      2024-01-03 09:09:00 0 days 00:32:00 -4.081835e+06  4.624822e+06
47      2024-01-03 08:06:00 0 days 00:52:00 -4.081811e+06  4.624681e+06
48      2024-01-02 08:40:00 0 days 03:19:00 -4.081832e+06  4.624809e+06
49      2024-01-02 05:54:00 0 days 02:07:00 -4.081806e+06  4.624911e+06
50      2024-01-01 21:15:00 0 days 03:55:00 -4.081810e+06  4.624908e+06
51      2024-01-01 18:17:00 0 days 02:41:00 -4.081796e+06  4.624789e+06
52      2024-01-01 15:04:00 0 days 01:12:00 -4.081693e+06  4.624739e+06